# Error Handling

### Working with try / except

In [3]:
# without try / except

first_num = float(input('% to calculate as decimal (provide a whole number): '))

pct_as_dec = first_num / 100

print(pct_as_dec)

% to calculate as decimal (provide a whole number):  bad value


ValueError: could not convert string to float: 'bad value'

In [7]:
# with try / except

try:
    first_num = float(input('% to calculate as decimal (provide a whole number): '))
    pct_as_dec = first_num / 100
except:
    print('Invalid input. Please try again.')
else:
    print(pct_as_dec)
finally:
    print('Run again to calculate another decimal value.')

% to calculate as decimal (provide a whole number):  bumblebee


Invalid input. Please try again.
Run again to calculate another decimal value.


In [15]:
try:
    fnum = float(input('Number to divide: '))
    snum = float(input('Second number to use as divisor: '))
    div_result = fnum / snum
except ValueError:
    print('Invalid input: must be a number. Please try again.')
except ZeroDivisionError:
    print('Cannot divide by zero.')
except:
    print('Encountered an error.')
else:
    print(div_result)
finally:
    print('Run again to calculate another decimal value.')

Number to divide:  47
Second number to use as divisor:  0


Cannot divide by zero.
Run again to calculate another decimal value.


In [18]:
# another alternative

try:
    fnum = float(input('Number to divide: '))
    snum = float(input('Second number to use as divisor: '))
    div_result = fnum / snum
except (ValueError, ZeroDivisionError):          # This is also a valid solution to the same problem
    print('Error: must be a number other than zero')
except:
    print('Encountered an error.')
else:
    print(div_result)
finally:
    print('Run again to calculate another decimal value.')

Number to divide:  48
Second number to use as divisor:  bumblebee


Error: must be a number other than zero
Run again to calculate another decimal value.


### can nest try / except blocks

In [21]:
try:
    f = open("sample_xyz.txt")   # if file not found, in "r" mode will throw an error
    try:
        sample_content = f.read()
    except: 
        print(f'Cannot read from file')
    else:
        print(sample_content)
    finally:
        f.close()
except:
    print("Error, cannot retrieve file")

Error, cannot retrieve file


In [22]:
try:
    f = open("sample.txt")  # still opening in "r" mode
    try:
        sample_content = f.write("\n")   # trying to write to the file
        sample_content = f.write("Customer survey was sent out via email mailing list.")
    except: 
        print(f'Cannot read from file')
    else:
        print(sample_content)
    finally:
        f.close()
except:
    print("Error, cannot retrieve file")

Cannot read from file


### using try / except with a loop

In [26]:
print('Division calculator:') 
first_n = None

while first_n == None:
    try:
        first_n = float(input('First number to divide: '))
    except:
        print('Invalid input! Must be a number')

second_n = None
answer = None

while second_n == None:
    try:
        second_n = float(input('Second number to divide by: '))  # this would not result in an error if number is zero
        answer = first_n / second_n
    except ValueError:
        print('Must be a number')
    except ZeroDivisionError:
        print('Number cannot be zero')
        second_n = None   # resets second_n to keep loop going

print(answer)

Division calculator:


First number to divide:  200
Second number to divide by:  0


Number cannot be zero


Second number to divide by:  11


18.181818181818183


In [30]:
print('Division calculator:') 
first_n = None

while first_n == None:
    try:
        first_n = float(input('First number to divide: '))
    except:
        print('Invalid input! Must be a number')

second_n = None
answer = None

while second_n == None:
    try:
        second_n = float(input('Second number to divide by: '))  # this would not result in an error if number is zero
        answer = first_n / second_n
    except:
        pass   # would terminate the loop so you get to the end of program, but it's less informative

print(answer)

Division calculator:


First number to divide:  111
Second number to divide by:  0


None


In [35]:
# another example of try / except combined with a loop that's operating on file contents

try:
    with open("sample2.txt") as f:    # if no sample2.txt then will trigger except block
        contents = f.readlines()
except FileNotFoundError:
    print('Error: file not found')
else:
    with open("sales_data.csv", "w") as output:
        for i in contents:
            if "," in i:
                output.write(i)
    print('Output complete.')
finally:
    print('Run program again to process another file.')

Error: file not found
Run program again to process another file.


# Working with NumPy

### Creating arrays

In [36]:
import numpy as np

a = np.array([11,12,13,14,15])

In [37]:
print(a)

[11 12 13 14 15]


In [38]:
print(type(a))

<class 'numpy.ndarray'>


In [39]:
b = np.array(100)  # zero-dimensional array

print(b)
print(type(b))

100
<class 'numpy.ndarray'>


In [40]:
c = np.array((('a', 'b', 'c'), ('d', 'e', 6)))  # tuple of tuples, starting with both string and int values

print(c)

[['a' 'b' 'c']
 ['d' 'e' '6']]


In [42]:
d = np.array(((1, 2, None),(3, 4, 5)))

print(d)

[[1 2 None]
 [3 4 5]]


In [44]:
d2 = np.array(((1, 2, np.nan),(3, 4, 5)))   # NumPy uses NaN (not a number)

print(d2)

[[ 1.  2. nan]
 [ 3.  4.  5.]]


In [45]:
bess_list = [
    ([(1,2,3)], [(4,5,6)]),
    ([(7,8,9)], [(10,11,12)]),
    ([(13,14,15)], [(16, 17, 18)])
]

e = np.array(bess_list)

print(e)

[[[[ 1  2  3]]

  [[ 4  5  6]]]


 [[[ 7  8  9]]

  [[10 11 12]]]


 [[[13 14 15]]

  [[16 17 18]]]]


In [46]:
print(e.ndim) # number of dimensions

4


In [47]:
print(e.size) # number of elements in the array

18


In [49]:
print(e.shape) # what is the size of each dimension, given as a tuple, listed from the outside to the inside

# from our starting list:
# bess_list = [
#     ([(1,2,3)], [(4,5,6)]),
#     ([(7,8,9)], [(10,11,12)]),
#     ([(13,14,15)], [(16, 17, 18)])
# ]
#    list inclues 3 items (3 tuples) -- outermost dimension
#    each tuple in the next layer contains 2 items (2 lists)
#    each list in the next layer contains 1 item (a tuple)
#    in the innermost tuple, there are 3 elements

(3, 2, 1, 3)


In [50]:
print(d2)
print(d2.ndim)
print(d2.size)
print(d2.shape)

[[ 1.  2. nan]
 [ 3.  4.  5.]]
2
6
(2, 3)


In [53]:
print(d2.T)  # transpose the dimensions of the array
print(d2.T.shape) 

[[ 1.  3.]
 [ 2.  4.]
 [nan  5.]]
(3, 2)


### using indexing with arrays

In [54]:
print(d2[0][0])  # returns the first value in the first dimension (zero position)

1.0


In [55]:
print(d2[1][1])

4.0


In [56]:
print(e)

[[[[ 1  2  3]]

  [[ 4  5  6]]]


 [[[ 7  8  9]]

  [[10 11 12]]]


 [[[13 14 15]]

  [[16 17 18]]]]


In [59]:
print(e[-1][-1][-1])  # using the index through 3 dimensions

[16 17 18]


In [60]:
print(e[-1][-1][-1][-1])  # using the index through 4 dimensions

18


In [62]:
print(e[1][1][0][1])

11
