## Continuing with NumPy

### Briefly, review of hstack / vstack / dstack

In [15]:
import numpy as np

a = np.array([0, 1, 2, 3, 11, 12])
b = np.array([4, 5, 6, 7, 13, 14])

print(np.hstack((a,b)))  # equivalent to concatenatating on the 0 axis
print(np.vstack((a,b)))  # equivalent to concatenating on the 1 axis
print(np.dstack((a,b)))  # equivalent to concatenating on the 2 axis

[ 0  1  2  3 11 12  4  5  6  7 13 14]
[[ 0  1  2  3 11 12]
 [ 4  5  6  7 13 14]]
[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]
  [11 13]
  [12 14]]]


In [16]:
print(np.concatenate((a,b)))

print(np.stack((a,b)))

print(np.stack((a,b), axis = 1))   # not equivalent to dstack, as dstack will return 3D array

[ 0  1  2  3 11 12  4  5  6  7 13 14]
[[ 0  1  2  3 11 12]
 [ 4  5  6  7 13 14]]
[[ 0  4]
 [ 1  5]
 [ 2  6]
 [ 3  7]
 [11 13]
 [12 14]]


In [17]:
# so splitting arrays is breaking arrays apart

print(np.array_split(a, 2))

[array([0, 1, 2]), array([ 3, 11, 12])]


In [18]:
print(np.array_split(a, 3))

[array([0, 1]), array([2, 3]), array([11, 12])]


In [ ]:
print(np.array_split(a, 4))  # allows for an uneven split

[array([0, 1]), array([2, 3]), array([11]), array([12])]


In [24]:
print(np.hsplit(a, 2))  # hsplit works on the 0 axis, is not forgiving of uneven splits

[array([0, 1, 2]), array([ 3, 11, 12])]


In [27]:
ab = np.stack((a,b))

print(ab)

print(np.vsplit(ab, 2))

[[ 0  1  2  3 11 12]
 [ 4  5  6  7 13 14]]
[array([[ 0,  1,  2,  3, 11, 12]]), array([[ 4,  5,  6,  7, 13, 14]])]


In [28]:
print(np.hsplit(ab, 2))

[array([[0, 1, 2],
       [4, 5, 6]]), array([[ 3, 11, 12],
       [ 7, 13, 14]])]


In [31]:
# let's put this into context with some sales data

full_year = np.array([[100, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220],
                      [200, 210, 190, 205, 220, 230, 240, 235, 225, 215, 205, 195],
                      [ 90,  95, 100, 110, 115, 120, 125, 130, 120, 115, 110, 105]])

# each array is a column
# the "rows" match on the vertical alignment

In [35]:
quarters = np.array_split(full_year, 4, axis = 1)
print(quarters)

q1, q2, q3, q4 = quarters
print(q1)

[array([[100, 120, 130],
       [200, 210, 190],
       [ 90,  95, 100]]), array([[140, 150, 160],
       [205, 220, 230],
       [110, 115, 120]]), array([[170, 180, 190],
       [240, 235, 225],
       [125, 130, 120]]), array([[200, 210, 220],
       [215, 205, 195],
       [115, 110, 105]])]
[[100 120 130]
 [200 210 190]
 [ 90  95 100]]


In [37]:
by_product = np.array_split(full_year, 3, axis = 0)

prod_a, prod_b, prod_c = by_product

print(prod_a)

[[100 120 130 140 150 160 170 180 190 200 210 220]]


### Using where() to apply a condition to an array

In [ ]:
print(np.where(full_year > 200))   # with only a condition, return an array of matches

(array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64), array([10, 11,  1,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64))


In [47]:
print(np.where(full_year > 200, 'high', full_year))  # lets you set a return and not-found value

[['100' '120' '130' '140' '150' '160' '170' '180' '190' '200' 'high'
  'high']
 ['200' 'high' '190' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
  'high' '195']
 ['90' '95' '100' '110' '115' '120' '125' '130' '120' '115' '110' '105']]


In [49]:
print(full_year[full_year > 200])  # filtering with bracket notation returns only matches

[210 220 210 205 220 230 240 235 225 215 205]


In [53]:
print(full_year[full_year % 3 == 0])   # can put condition directly in brackets

[120 150 180 210 210 240 225 195  90 120 120 105]


In [54]:
div_by_3 = (full_year % 3 == 0)

print(full_year[div_by_3])   # this is the pattern on p. 15 in the Student Guide

[120 150 180 210 210 240 225 195  90 120 120 105]


### Sorting array values

In [55]:
num_x = np.array([(7,6,2,1,9),(5,3,9,1,0)])

In [59]:
num_sorted = np.sort(num_x)   # sort() will return a copy of the array with sorting applied

In [61]:
print(num_x)
print(num_sorted)

[[7 6 2 1 9]
 [5 3 9 1 0]]
[[1 2 6 7 9]
 [0 1 3 5 9]]


In [66]:
str_x = ('I-1456', 'InstaDerp', '110-XR', '#Zenith', '012', '014', '110', 145, '008')
str_x = np.array(str_x)
print(str_x)

['I-1456' 'InstaDerp' '110-XR' '#Zenith' '012' '014' '110' '145' '008']


In [67]:
print(np.sort(str_x))

['#Zenith' '008' '012' '014' '110' '110-XR' '145' 'I-1456' 'InstaDerp']


## Random in NumPy

In [68]:
# when calling the random module in NumPy:
# np.random.[function name]

In [71]:
some_ints = np.random.randint(100, size = (5))  # assumes a zero start == from 0 to 100
print(some_ints)

[86  2 54 23 68]


In [72]:
more_ints = np.random.randint(50, 100, size = (5, 3))  # assumes a zero start == from 0 to 100
print(more_ints)

[[88 89 94]
 [91 72 93]
 [76 60 54]
 [85 78 79]
 [69 60 73]]


In [73]:
print(np.random.rand(5, 3))

[[0.26176894 0.47204139 0.34773709]
 [0.6672206  0.18186866 0.0219563 ]
 [0.40610019 0.76052033 0.08401442]
 [0.35784227 0.05182094 0.13765501]
 [0.68265688 0.17965763 0.9587499 ]]


In [77]:
# working with choice()

print(some_ints)  # starting values to choose from
print(np.random.choice(some_ints))

[86  2 54 23 68]
86


In [79]:
sales_sample = np.random.choice(str_x, size = (4, 10))

print(sales_sample)

[['012' '110-XR' 'InstaDerp' '110-XR' 'I-1456' 'I-1456' '014' '008' '012'
  '012']
 ['014' '#Zenith' '110' '145' 'I-1456' 'InstaDerp' '110' '#Zenith'
  'I-1456' '#Zenith']
 ['145' '014' '012' '012' '014' '014' '110-XR' '#Zenith' '110' '#Zenith']
 ['110-XR' 'I-1456' '014' '110-XR' '110-XR' 'InstaDerp' '014' '110-XR'
  '110' '014']]


In [81]:
# choice() can also be used to assign probability values

weighted_sales_sample = np.random.choice(str_x, size = (4, 10), 
                                         p = [.1, .2, .2, .2, .1, .05, .05, .05, .05])

print(weighted_sales_sample)

[['InstaDerp' 'I-1456' 'InstaDerp' '110-XR' '110-XR' 'InstaDerp' 'I-1456'
  'InstaDerp' 'I-1456' '110-XR']
 ['InstaDerp' '012' 'InstaDerp' '#Zenith' '110-XR' 'InstaDerp' '110-XR'
  '110-XR' '014' '110']
 ['#Zenith' 'I-1456' 'InstaDerp' 'InstaDerp' 'I-1456' 'I-1456' '110-XR'
  '#Zenith' '012' '#Zenith']
 ['014' '#Zenith' '#Zenith' '110-XR' '110-XR' 'InstaDerp' '008' '008'
  '012' '008']]


In [83]:
# for starting values: 
# ['I-1456' 'InstaDerp' '110-XR' '#Zenith' '012' '014' '110' '145' '008']
# assigned p values:
#       .1          .2       .2        .2    .1   .05   .05   .05   .05

### Creating a distribution curve using normal() 

In [87]:
x = np.random.normal(loc=5, scale=2, size=(30))

print(x)

[2.4555076  4.93336577 5.2059771  4.89724822 6.17929931 6.8095894
 6.73565805 6.35888118 3.41291441 5.81412998 3.82082663 1.6313159
 6.61626111 6.84336976 5.84970561 6.15616042 6.62554684 5.34773001
 1.59575935 6.40337557 5.56780696 4.00078509 3.29434837 2.45960269
 5.22324439 1.39439544 6.25744065 5.34231029 5.55890768 1.57529899]


### Shuffle / Permutation

In [88]:
print(str_x)

['I-1456' 'InstaDerp' '110-XR' '#Zenith' '012' '014' '110' '145' '008']


In [89]:
# permutation will return a new array / a copy with the results in a new order

print(np.random.permutation(str_x))

['145' '012' '#Zenith' 'I-1456' '008' '014' '110' '110-XR' 'InstaDerp']


In [90]:
print(str_x)

['I-1456' 'InstaDerp' '110-XR' '#Zenith' '012' '014' '110' '145' '008']


In [91]:
# shuffle is an in-place operation that changes the order of the starting array

print(np.random.shuffle(str_x))

print(str_x)

None
['#Zenith' '014' '012' '008' 'InstaDerp' '110-XR' '110' 'I-1456' '145']


## ufuncs in NumPy

In [92]:
sale_price = np.array([2.99, 12.99, 3.50, 4.50, 17.99, 22.00])

discount_amount = np.array([0, 0, 3.50, .50, 3, 0])

print(sale_price + discount_amount)

[ 2.99 12.99  7.    5.   20.99 22.  ]


In [93]:
print(np.add(sale_price, discount_amount))

[ 2.99 12.99  7.    5.   20.99 22.  ]


In [97]:
print(np.multiply(sale_price, .8))

# print(np.multiply(sale_price, 1 - .2))  # another common format for calculating % discount

[ 2.392 10.392  2.8    3.6   14.392 17.6  ]


In [100]:
print(np.round(np.multiply(sale_price, .8), 2))

[ 2.39 10.39  2.8   3.6  14.39 17.6 ]


In [107]:
# round() applies "banker's rounding"
# rounding at 5 rounds towards the nearest even value

apple = np.array((.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5))

print(np.round(apple))

print(sum(np.round(apple)))


# numpy also has a function called around() ... which is just an alias for round()

[0. 2. 2. 4. 4. 6. 6.]
24.0


In [106]:
# compare to conventional round in Python

babble = [.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5]

print(round(sum(babble)))

24


## Using sum() / cumsum() / prod() / cumprod()

In [108]:
# sum() adds up elements of an array

print(np.sum(apple))

24.5


In [109]:
pear = np.random.rand(5, 3)
print(pear)

[[0.96132587 0.83055465 0.91536921]
 [0.60994387 0.82617501 0.77560785]
 [0.45242584 0.43904997 0.58926992]
 [0.92533808 0.59160961 0.83184272]
 [0.57076819 0.77377499 0.78536271]]


In [110]:
print(np.sum(pear))

10.878418493543824


In [113]:
print(np.sum(pear, axis=1))  
# since arrays can have multiple dimensions, you might want to sum on another axis

[2.70724973 2.21172673 1.48074573 2.34879041 2.12990589]


In [114]:
print(np.cumsum(pear))

[ 0.96132587  1.79188052  2.70724973  3.3171936   4.14336862  4.91897647
  5.3714023   5.81045228  6.39972219  7.32506027  7.91666989  8.7485126
  9.3192808  10.09305578 10.87841849]


In [115]:
print(np.cumsum(pear, axis=1))

[[0.96132587 1.79188052 2.70724973]
 [0.60994387 1.43611888 2.21172673]
 [0.45242584 0.89147581 1.48074573]
 [0.92533808 1.51694769 2.34879041]
 [0.57076819 1.34454318 2.12990589]]


In [117]:
print(np.sum(pear, axis=1))

[2.70724973 2.21172673 1.48074573 2.34879041 2.12990589]


In [120]:
# similarly, prod() gives all elements multiplied together
# and cumprod() will give a rolling product

print(np.prod(pear))

0.005281247187788603


In [121]:
print(np.prod(pear, axis=1))

[0.7308616  0.3908446  0.11705113 0.45538307 0.34685242]


In [123]:
print(np.cumprod(pear))

[0.96132587 0.79843368 0.7308616  0.44578455 0.36829606 0.28565331
 0.12923694 0.05674148 0.03343604 0.03093965 0.01830419 0.01522621
 0.00869064 0.0067246  0.00528125]


In [125]:
# diff() provides the difference in values (as in subtraction)
# between elements in an array

print(sale_price)

print(np.diff(sale_price))

[ 2.99 12.99  3.5   4.5  17.99 22.  ]
[10.   -9.49  1.   13.49  4.01]


In [127]:
print(np.diff(sale_price, n=2))

[-19.49  10.49  12.49  -9.48]


In [132]:
print(np.diff(sale_price, n=5))

[4.01]
